.TH RIVER-ULTITILE 1 2022-04-23 sr.ht/~midgard/river-ultitile
.
.SH NAME
.B river-ultitile
\- tiled layout generator for
.BR river (1)
.
.SH SYNOPSIS
.SY river-ultitile
.YS
.
.SY river-ultitile
.OP \-h
.OP \-\-version
.YS
.
.SH DESCRIPTION
.B river-ultitile
is a fork of
.BR rivertile (1)
layout generator for
.BR river (1).
.P
It provides a configurable layout
.
.SH OPTIONS
.TP
.B \-h
Print a help message and exit.
.TP
.B \-\-version
Print the version number and exit.
.TP
.
.SH SEE ALSO
.P
.al
.nh
.BR river (1),
.BR riverctl (1),
.BR rivertile (1),
.BR rivercarro (1),
.
