#!/bin/sh
set -u
IFS=" "

while read line; do
	set $line
	case "$1" in
		"center-main-views") echo "set center-main.root.main maxviews$2"; ;;
		"left-main-views") echo "set left-main.root.main maxviews$2"; ;;
	esac
done
