#!/bin/sh

echo "new layout main-left type=hsplit stretch=1"
echo "new tile main-left.left type=vsplit stretch=40 order=2"
echo "new tile main-left.main type=vsplit stretch=60 order=1 max-views=1"

echo "new layout main-center type=hsplit stretch=1"
echo "new tile main-center.left type=vsplit stretch=25 order=2 suborder=0"
echo "new tile main-center.main type=vsplit stretch=50 order=1 max-views=1"
echo "new tile main-center.right type=vsplit stretch=25 order=2 suborder=1"

echo "new layout monocle type=hsplit stretch=1 order=1 max-views=1"
